### ISSUE TITLE
[Feature] Recurring events

### ISSUE THREAD

**Issue by NicoCG** [gldraphael/evlog#57]
Ability to add recurring events on certain days of the week. Example x event will show every Monday and Saturday.

You could have something in dB 

Repeat = ‘monday, tuesday, saturday’ 
And
Repeat = ‘never’

**Comment by gldraphael** [comment]
This is not something I'd like to do for now. Maybe for v1 perhaps.

**Comment by NicoCG** [comment]
Okay 👌 sounds good but instead of closing it should rather add it as v1 milestone or as idea 💡

**Comment by gldraphael** [comment]
Not for v1.
