### ISSUE TITLE
MVC views

### ISSUE THREAD

**Issue by nicotravassos** [gldraphael/evlog#75]
Hi @gldraphael,

Please could you convert this project to use MVC structure and not razor pages.

**Comment by gldraphael** [comment]
No I've chosen to use Razor pages for pages. Will use controllers for APIs only.

What's your usecase? Because as far as I understand everything possible with MVC is also possible with razor pages.

**Comment by nicotravassos** [comment]
@gldraphael  Sorry ignore my request I have look at differences and benefits and I think maybe razor is a best fit for this project
